config/routes.rb
Rails.application.routes.draw do

   root 'sessions#new'
   resources :users
   resource :session, only: [:new, :create] do
    get :logout
  end
    resources :blog_lists, only: [:index, :new, :create, :show] do
      collection do
       get 'my_blogs' # /products/:id/short   post 'toggle'
      end
    resources :comments, only: [:destroy, :create]
    end
    
    

   

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
end

app/models/blog_list.rb
class BlogList < ActiveRecord::Base
	validates :name, presence: true
	validates :content, presence: true
	belongs_to :user
	has_many  :comments
	self.per_page = 2
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :message, presence: true
	validates :message, length: { maximum: 50 }
	belongs_to :blog_list
end

app/models/community.rb
class Community < ActiveRecord::Base
	validates :name, presence: true
	validates :name, uniqueness: true
  has_and_belongs_to_many :users, join_table: :community_users
end

app/models/role.rb
class Role < ActiveRecord::Base
	validates :name, presence: true
	validates :name, uniqueness: true
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base

	validates :first_name, :last_name, :email, :password, presence: true
  validates :email, uniqueness: true
  validate  :email_regex
  validates :password, length: { in: 8..16 }
  validate :password_validation
  has_many  :blog_lists
  has_and_belongs_to_many  :communities, join_table: :community_users
  has_one :address
  has_and_belongs_to_many :roles
  self.per_page = 2
  after_create :send_email

  def name
 	  first_name + "	" + last_name
  end


  def email_regex
    if email.present? and not email.match(/\A[^@]+@[^@]+\z/)
      errors.add :email, "This is not a valid email format"
    end
  end


  def password_validation
    if password.present? and not password.match(/^(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$/)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
    end
  end

  def compute_fullname 
    fullname = (self.first_name+self.last_name)
  end
  def send_email
    UserMailer.welcome(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
  end
  def logged_in?
	  redirect_to new_session_path if session[:current_user_id].blank?
	end
end

app/controllers/blog_lists_controller.rb
class BlogListsController < ApplicationController
before_action :logged_in?  
before_action :current_user, only: [:create, :my_blogs]
  def index
  	@blogs=BlogList.paginate(page: params[:page]).all
  end

	def new	
		@blog=BlogList.new
	end

	def create
		@blog = current_user.blog_lists.new(blog_params)
		if @blog.save
		 	flash[:notice] = "blog saved successfully"
		 	redirect_to action: "show", id: blog.id
		else
			flash[:notice] = @blog.errors.full_messages
		end
		render :new
	end

	def show
    @blog=BlogList.find_by(id: params[:id])
    @comments = @blog.comments
  end

	def my_blogs
		@my_blogs = current_user.blog_lists.paginate(page: params[:page])
	end

	private
  def blog_params
		params.require(:blog_list).permit(:name, :content)
	end	
end

app/controllers/blogs_lists_controller.rb
class BlogsListsController < ApplicationController
	def new
	end
	def create
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :logged_in?
  def new
   @comment=Comment.new
  end

  def create
   blog = BlogList.find_by(id: params[:blog_list_id])
    comment = blog.comments.new(comment_params)
    comment.user_id = current_user.id
    if comment.save
      flash[:notice] = "Comment saved!!!"
    else
      flash[:notice] = comment.errors.full_messages
    end
    redirect_to blog
  end

  def destroy
    comment = Comment.find_by(id: params[:id])
    blog = comment.blog_list
    comment.destroy
    flash[:notice] = "Comment deleted successfully"
    redirect_to blog
  end

  private
  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to controller: :users, action: :show, id: current_user.id
    end 
  end
  def create
  	user = User.find_by(username: params[:username], password: params[:password])
  	if user
  		flash[:notice]="Login Successful"
  		session[:current_user_id] = user.id
  		redirect_to controller: :users, action: :show, id: user.id
  	else
  		flash[:notice]="Invalid Credentials"
  		redirect_to action: :new
    end
  end

  def logout
  	session.clear
  	flash[:notice] = "Succesfully Logged out."
  	redirect_to :new_session
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :get_user_id, only: [:show, :edit, :update]
  before_action :logged_in?, except: [:new, :create]
 	
	def index
	  @users=User.paginate(page: params[:page]).order("created_at DESC")
	end
	def new
	  @user=User.new
	end
	def create
	  @user=User.new(user_params)
	    if @user.save
	      flash[:notice] = "Record Saved Succesfullly"
	      redirect_to action: "show", id: @user.id
      else
	      flash[:notice] = "Error in saving Record"
	      render :new
	    end
	end
	def edit
	end
	def update  
		if @user.update_attributes(user_params)
		  flash[:notice] = "Record updated successfully"
		  redirect_to action: "show", id: @user.id
		else
		  flash[:notice] = "Error in updating the record"
	    render :edit
		end
	end

	def show

	end

	def destroy
	end

	private
	def user_params	
	  params.require(:user).permit(:first_name,:last_name,:username,:password,:active,:email)#strong parameters
	end
  def get_user_id
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_lists_helper.rb
module BlogListsHelper
end

app/helpers/blogs_lists_helper.rb
module BlogsListsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_lists/_blog_list.html.erb
<table class='table'>
  <th><tr><td><strong>name</strong></td><td><strong>content</strong></td><td><strong>user</strong></td><td><strong>created time</strong></td><td><strong>Action1</strong></td><td><strong>Action2</strong></td></tr>  </th>
  <% blogs.each do |blog| %>
  <tr>
  <td>
    <%= blog.name %>
  </td>
  <td>
    <%= blog.content %> 
  </td>
  <td>
    <%= blog.user.first_name %>
  </td> 
  <td>
    <%= time_ago_in_words(blog.created_at) %>
  </td>
  <td>
    <%= link_to "Show blog", blog_list_path(id: blog.id) %>
  </td>
  <td>
    <%= link_to "Post comment", blog_list_path(id: blog.id) %>
  </td>
  </tr>
  <% end %>
</table>
  <%= will_paginate blogs %>
  <p> <%= link_to "Create a blog", new_blog_list_path %></p>

app/views/blog_lists/_blog_show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= blog.name %></h3>
  </div>
  <div class="panel-body">
    <%= blog.content %>
  </div>
</div>

app/views/blog_lists/index.html.erb
<%= render partial: "blog_list", locals: { blogs: @blogs } %>

app/views/blog_lists/my_blogs.html.erb
<%= render partial: "blog_list", locals: { blogs: @my_blogs }%>

app/views/blog_lists/new.html.erb
<h2>Enter the Blog name</h2>
<% if flash[:notice]%>
  <div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= flash[:notice] %>
  <% end %>
</div>
  <%= form_for @blog do |f| %>
  <div class='form-horizontal row col-xs-3'>
  <div class = "form-group">
    <%= label_tag 'name', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.text_field :name, class: "form-control col-sm-offset-1", placeholder: "Enter blog name" %>
  </div>	
  <div class = "form-group">
    <%= label_tag 'content', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.text_area :content, class: "form-control col-sm-offset-1", rows: "5", placeholder: "Enter content" %>
  </div>
  <div class = "form-group">
    <div class="col-sm-offset-1">
      <%= f.submit :"save the post" , class: "btn btn-primary" %>
    </div>
  </div>	
<% end %>

app/views/blog_lists/show.html.erb
<% if flash[:notice]%>
  <div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= flash[:notice] %>
<% end %>
</div>
<div class="row">
  <%= render partial: "blog_show", locals: { blog: @blog } %>
</div>
<div class="row col-sm-offset-0">
  <%= render partial: "/comments/new_comment", locals: {blog: @blog}%>
</div>
<div class = "row">
  <%= render partial: "comments/list", collection: @comments, as: "comment" %>
</div>
<br/>
<div class="row col-sm-offset-0">
  <%= link_to "Create a blog", new_blog_list_path, class: "btn btn-primary btn-lg active", role: "button" %>
</div>

app/views/comments/_list.html.erb
<div class= "row">
  <div class="col-md-1"></div>
  <div class="col-md-5">
    <%= comment.message %>
  </div>
  <div class = "col-md-2">
    <%= link_to blog_list_comment_path(comment.blog_list.id, comment.id), method: :delete  do %>
     <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
    <% end %>
  </div>
</div>

app/views/comments/_new_comment.html.erb
<%= form_for :comment, url: blog_list_comments_path(blog.id), class: "form-inline" do |f| %>
  <div class="col-sm-6">
    <%=f.text_area :message, class: 'form-control col-sm-6', placeholder: "Enter the comment"  %>
  </div>
<%= f.submit  "Enter comment", class: "btn btn-primary btn"%>
<% end %>

app/views/comments/new.html.erb
<div>
  <%= render partial: "/blog_lists/blog_show", object: @blog %>
</div>
<div class="row">
  <%= render partial: "new_comment", locals: {comment: @comment } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class= "nav nav-tabs" >
  <% if session[:current_user_id] %>
    <% active = current_page?(controller: 'users', action: 'show', id: session[:current_user_id]) ? "active" : ""%>
    <li role="presentation" class = "#{active}">     
    <%= link_to "View my profile", user_path(session[:current_user_id]) %>
    </li>
    <% if (controller.controller_name == "blog_lists" &&  controller.action_name != "index") %>
    <li role= "presentation" > <%= link_to "View blogs", blog_lists_path %> </li>
    <% end %>
    <% if (controller.controller_name != "blog_lists" &&  controller.action_name != "my_blogs") %>
    <li role = "presentation"><%= link_to "View my blogs", my_blogs_blog_lists_path %> </li>
    <% end %>
    <li role="presentation"> <%= link_to "Logout", logout_session_path %> </li> 
  <%end%>
</ul>
<div class = "content">
  <%= yield %>
</div>
</body>
</html>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<% @user.errors.full_messages.each do|msg| %>
<%= msg %>
<% end %>
<% end %>
<div class='form-horizontal row col-xs-3'>
  <div class = "form-group">
    <%= label_tag 'firstname', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.text_field :first_name, class: "form-control col-sm-offset-1", placeholder: "Enter first name" %>
  </div>
  <div class = "form-group">
    <%= label_tag 'Lastname', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.text_field :last_name, class: "form-control col-sm-offset-1", placeholder: "Enter last name" %>
  </div>
  <div class = "form-group">
    <%= label_tag 'email', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.text_field :email, class: "form-control col-sm-offset-1", placeholder: "Enter email" %>
  </div>
  <div class = "form-group">
    <%= label_tag 'username', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.text_field :username, class: "form-control col-sm-offset-1", placeholder: "Enter user name" %>
  </div>
  <div class = "form-group">
    <%= label_tag 'password', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.password_field :password, class: "form-control col-sm-offset-1", placeholder: "Enter password" %>
  </div>
  <div class="form-inline form-group">
    <div class="checkbox col-sm-offset-1">
      <label>Active</label>
        <%= f.check_box :active %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag "File Input", nil, class: "col-sm-offset-1" %>
    <%= f.file_field :image, class:"col-sm-offset-1" %>
  </div>
  <div class = "form-group">
    <div class="col-sm-offset-1">
      <%= f.submit :submit , class: "btn btn-primary" %>
    </div>
  </div>
<%end%>

app/views/users/index.html.erb
<table>
  <% @users.each do |user| %>

  <tr>
	  <td>First name</td>
	  <td><%= user.first_name%></td>
	</tr>
  <tr>
	  <td>Last Name</td>
 	  <td><%= user.last_name%></td>
	</tr>
  <tr>
    <td>Email</td>
		<td><%= user.email%></td>
	</tr>
  <tr>
    <td>User Name</td>
		<td><%= user.username%></td>	
	</tr>
  <tr>
    <td>Status</td>
    <td><%= user.active%></td>	
  </tr>
  <% end %>
</table>
<p> <%= link_to "New user", new_user_path %>
</p>
<p>
  <%= link_to "Logout",logout_session_path %></p>
  <%= will_paginate @users %>
</p>

app/views/users/new.html.erb
<div class="col-sm-offset-1">Hello there!</div>
  <%= form_for @user do |f|%>
  <% if @user.errors.any? %>
  <% @user.errors.full_messages.each do|msg| %>
  <p class="form-group has-error"><%= msg %></p>
  <% end %>
  <% end %>
  <div class='form-horizontal row col-xs-3'>
  <div class = "form-group">
    <%= label_tag 'firstname', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.text_field :first_name, class: "form-control col-sm-offset-1", placeholder: "Enter first name" %>
  </div>
  <div class = "form-group">
    <%= label_tag 'lastname', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.text_field :last_name, class: "form-control col-sm-offset-1", placeholder: "Enter last name" %>
  </div>
  <div class = "form-group">
    <%= label_tag 'email', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.text_field :email, class: "form-control col-sm-offset-1", placeholder: "Enter your email address" %>
  </div>
  <div class = "form-group">
    <%= label_tag 'username', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.text_field :username, class: "form-control col-sm-offset-1", placeholder: "Enter Username"%>
  </div>
  <div class = "form-group">
    <%= label_tag 'password', nil, class: 'col-sm-offset-1 control-label' %>
    <%= f.password_field :password, class: "form-control col-sm-offset-1", placeholder: "Enter password" %>
  </div> 
  <div class="form-inline form-group">
    <div class="checkbox col-sm-offset-1">
      <label>Active</label>
        <%= f.check_box :active %>
    </div>
  </div>
  <div class = "form-group">
    <div class="col-sm-offset-1">
      <%= f.submit :submit , class: "btn btn-primary" %>
    </div>
  </div>
<%end%>

app/views/users/show.html.erb
<table>
  <tr>
	  <td>First name:</td>
	  <td><%= @user.first_name%></td>
	</tr>
  <tr>
	  <td>Last Name:</td>
 	  <td><%= @user.last_name%></td>
	</tr>
  <tr>
    <td>Email:</td>
		<td><%= @user.email%></td>
	</tr>
  <tr>
    <td>User Name:</td>
		<td><%= @user.username%></td>	
	</tr>
  <tr>
    <td>Status:</td>
  <td>
		<%= @user.active%>
	</td>	
	</tr>

</table>
  <% if session[:current_user_id] == @user.id %>
  <p> <%= link_to "Edit", edit_user_path(@user.id) %>
  </p>
<% end %>